# -*- coding: utf-8 -*-
"""Copy of print_and_variables_assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OTnv3L5SY-Pyv8Ti_8z-xpDfDwbAQdjD

<a href="https://colab.research.google.com/github/ubaid978/AI-Notebooks/blob/main/Copy_of_print_and_variables_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""



"""## Write a Python program to print your name."""

print("Name: Muhamad Ahmed")

"""## Print your age and city on separate lines."""

print("Age: 20" , "City: Karachi" , sep="\n")

"""## Print the following sentence exactly:
    Python is fun!
"""

print("Python is fun!")

"""## Print your name, age, and country in a single line using one print() statement."""

print("Name: Muhamad Ahmed" , "Age: 20" , "Country: Pakistan" , sep=",")

"""## Print three numbers in one line separated by spaces."""

print(1, 2, 3, sep=" ")

"""## Print apple, banana, mango separated by |"""

print("apple", "banana", "mango", sep="|")

"""## Create a variable name and assign your full name to it. Print the value of the variable."""

name = "Muhamad Ahmed"
print(name)

"""## Create a variable age and assign your age to it. Print the variable."""

age = 20
print(age)

"""## Create a variable city with any city name. Change its value to another city and print it before and after the change."""

city = "Karachi"
print(city)
city = "Lahore"
print(city)

"""## Create two variables x and y and assign them the values 5 and 7. Print their sum."""

x , y = 5 , 7
print(5+7)

"""## Assign the result of 7 * 8 to a variable result and print it."""

result = 7*8
print(result)

"""## Assign an integer 10 to x and a float 2.5 to y. Print the type of both variables using type()."""

x = 10
y = 2.5
print(type(x))
print(type(y))

"""## Assign True to a variable is_active."""

is_active = True
print(is_active)

"""## Assign the same value 100 to three variables x, y, z in a single line."""

x = y = z = 100
print(x,y,z)

"""## Assign 3.14 to a variable pi. What type is pi?"""

pi = 3.14
print(type(pi))